name: Build Kivy Android App (Docker Final Fix)

on:
  push:
    branches: [ "main" ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # --- নতুন এবং চূড়ান্ত সমাধান ---
    # ডকারের বিল্ড এনভায়রনমেন্ট সেটআপ এবং আপডেট করা
    # এটি 'unsupported media type' সমস্যার সমাধান করবে
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build with Docker and accept licenses
      run: |
        # Kivy-র অফিসিয়াল অ্যান্ড্রয়েড বিল্ড ডকার ইমেজটি ব্যবহার করা হচ্ছে
        # এইবার ডকার ক্লায়েন্ট আপডেট থাকায় ইমেজটি সঠিকভাবে ডাউনলোড হবে
        docker run --rm \
          -v "$(pwd)":/app \
          kivy/buildozer:latest \
          bash -c "yes | buildozer --verbose android debug"

    - name: Upload Artifact (APK)
      uses: actions/upload-artifact@v4
      with:
        name: freefire-mobile-apk
        path: bin/*.apk
        
