name: Build Kivy Android App (The Simple Way)

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    # ... আগের ধাপগুলো একই থাকবে ...

    - name: Build with Buildozer and accept licenses
      run: |
        # --- নতুন এবং গুরুত্বপূর্ণ লাইন ---
        # পুরনো এবং সম্ভাব্য সমস্যাযুক্ত বিল্ড ফাইলগুলো ডিলিট করে দেবে
        buildozer android clean
        
        # এখন একটি পরিষ্কার পরিবেশ থেকে বিল্ড শুরু হবে
        yes | buildozer --verbose android debug
        
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java (JDK 17)
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install buildozer and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip build-essential git python3-dev libsdl2-2.0-0 libsdl2-image-2.0-0 libsdl2-mixer-2.0-0 libsdl2-ttf-2.0-0
        pip install "cython==0.29.36" buildozer

    - name: Build with Buildozer and accept licenses
      run: |
        # Buildozer প্রথমবার চালানোর সময় SDK ডাউনলোড করবে
        # আমরা এই প্রক্রিয়াটিকে একটি স্ক্রিপ্টের মাধ্যমে চালাব যা স্বয়ংক্রিয়ভাবে 'y' চাপবে
        yes | buildozer --verbose android debug
        
