name: Build Kivy Android App (Final Corrected Version)

on:
  push:
    branches: [ "main" ] # আপনার ব্রাঞ্চের নাম 'main'

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java (JDK 17)
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install buildozer and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip build-essential git python3-dev libsdl2-2.0-0 libsdl2-image-2.0-0 libsdl2-mixer-2.0-0 libsdl2-ttf-2.0-0
        pip install "cython==0.29.36" buildozer

    - name: Build with Buildozer and accept licenses
      run: |
        # Buildozer প্রথমবার চালানোর সময় সঠিক spec ফাইল অনুযায়ী SDK ডাউনলোড করবে
        # 'yes' কমান্ডটি স্বয়ংক্রিয়ভাবে লাইসেন্স গ্রহণ করবে
        yes | buildozer --verbose android debug

    - name: Upload Artifact (APK)
      uses: actions/upload-artifact@v4
      with:
        name: freefire-mobile-apk
        path: bin/*.apk
        
