name: Build Android APK (The Final Fix)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    # --- মূল এবং চূড়ান্ত সমাধান ---
    - name: Build with Buildozer Action
      uses: ArtemSBulgakov/buildozer-action@v1
      with:
        # এই লাইনটি 'chown: invalid user: ‘user’' সমস্যার সমাধান করবে
        user: root
        
        # আমরা spec ফাইলকে বিশ্বাস করছি, তাই এখানে আর কিছু নির্দিষ্ট করার প্রয়োজন নেই
        command: buildozer android debug

    - name: Verify APK creation
      run: |
        if [ -f bin/*.apk ]; then
          echo "APK successfully created!"
          ls -la bin/
        else
          echo "Error: APK file not found!"
          exit 1
        fi
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: bin/*.apk
        retention-days: 30
        
    - name: Create Release (on tag push)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: bin/*.apk
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
