name: Build Kivy Android App (Docker-Based Final Attempt)

on:
  push:
    branches: [ "main" ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # আমরা আর Java বা Python সেটআপ করব না, কারণ সবকিছু ডকার ইমেজের ভেতরেই আছে।

    - name: Build with Docker and accept licenses
      run: |
        # Kivy-র অফিসিয়াল অ্যান্ড্রয়েড বিল্ড ডকার ইমেজটি ব্যবহার করা হচ্ছে
        docker run --rm \
          -v "$(pwd)":/app \
          kivy/buildozer:latest \
          bash -c "yes | buildozer --verbose android debug"

    - name: Upload Artifact (APK)
      uses: actions/upload-artifact@v4
      with:
        name: freefire-mobile-apk
        path: bin/*.apk
        
