name: Build MINI FIRE APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git unzip openjdk-11-jdk \
          python3-pip autoconf libtool \
          pkg-config zlib1g-dev \
          libncurses5-dev libncursesw5-dev \
          libtinfo5 cmake libffi-dev libssl-dev \
          ninja-build
        
    - name: Install Buildozer
      run: pip install buildozer cython
        
    - name: Setup Android SDK
      run: |
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
        mkdir -p android-sdk
        unzip commandlinetools-linux-8512546_latest.zip -d android-sdk
        mkdir -p android-sdk/cmdline-tools/latest
        mv android-sdk/cmdline-tools/* android-sdk/cmdline-tools/latest/
        export ANDROID_SDK_ROOT=$PWD/android-sdk
        export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools
        echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
        echo "PATH=$PATH" >> $GITHUB_ENV
        
    - name: Accept Android licenses
      run: |
        yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
        
    - name: Build APK with Buildozer
      run: |
        buildozer android clean
        buildozer android debug
        ls -la bin/
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: mini-fire-apk
        path: bin/*.apk
