name: Build Kivy Android App (Final Version)

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    # ধাপ ১: আপনার রিপোজিটরির কোড চেকআউট করা
    - name: Checkout code
      uses: actions/checkout@v4

    # ধাপ ২: Java Development Kit (JDK 17) সেটআপ করা
    - name: Set up Java (JDK 17)
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    # ধাপ ৩: Python 3.9 সেটআপ করা
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # ধাপ ৪: Android SDK এবং NDK সেটআপ করা (সর্বশেষ সংস্করণ ব্যবহার করে)
    # --- এটিই মূল পরিবর্তন: v3 থেকে v4 এ আপগ্রেড করা হয়েছে ---
    - name: Setup Android SDK
      uses: android-actions/setup-android@v4.0.0 # <--- এখানে পরিবর্তন করা হয়েছে

    # ধাপ ৫: Buildozer এবং এর জন্য প্রয়োজনীয় লাইব্রেরি ইনস্টল করা
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install "cython==0.29.36"
        pip install buildozer

    # ধাপ ৬: Buildozer দিয়ে অ্যান্ড্রয়েড ডিবাগ APK তৈরি করা
    - name: Build with Buildozer
      run: |
        buildozer --version
        buildozer --verbose android debug

    # ধাপ ৭: বিল্ড হওয়া APK ফাইলটিকে আর্টিফ্যাক্ট হিসেবে আপলোড করা
    - name: Upload Artifact (APK)
      uses: actions/upload-artifact@v4
      with:
        name: freefire-mobile-apk
        path: bin/*.apk
        
