name: Build Kivy Android App with Licenses

on:
  push:
    branches: [ "main" ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    # ধাপ ১: আপনার রিপোজিটরির কোড চেকআউট করা
    - name: Checkout code
      uses: actions/checkout@v4

    # ধাপ ২: Java Development Kit (JDK 11) সেটআপ করা
    - name: Set up Java (JDK 11)
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'

    # ধাপ ৩: Python 3.9 সেটআপ করা
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # ধাপ ৪: Android SDK এবং NDK সেটআপ করা এবং স্বয়ংক্রিয়ভাবে লাইসেন্স গ্রহণ করা
    # --- এটিই মূল সমাধান ---
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3.2.1

    # ধাপ ৫: Buildozer এবং এর জন্য প্রয়োজনীয় লাইব্রেরি ইনস্টল করা
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install "cython==0.29.36" # একটি নির্দিষ্ট ও স্থিতিশীল Cython ভার্সন
        pip install buildozer

    # ধাপ ৬: Buildozer দিয়ে অ্যান্ড্রয়েড ডিবাগ APK তৈরি করা
    - name: Build with Buildozer
      run: |
        # Buildozer কে বলে দেওয়া হচ্ছে যে SDK পাথ পরিবর্তন হয়েছে
        # এটি নিশ্চিত করে যে Buildozer নিজে থেকে SDK ডাউনলোড করার চেষ্টা করবে না
        buildozer --version
        buildozer --verbose android debug

    # ধাপ ৭: বিল্ড হওয়া APK ফাইলটিকে আর্টিফ্যাক্ট হিসেবে আপলোড করা
    - name: Upload Artifact (APK)
      uses: actions/upload-artifact@v4
      with:
        name: freefire-mobile-apk
        path: bin/*.apk
        
