            - name: Buildozer cython
  # You may pin to the exact commit or the version.
  # uses: 102757017/buildozer-action@49cb3ff7a94238f0dab11058bf5c4c997d15bfcd
  uses: 102757017/buildozer-action@v1
  with:
    # Command to start Buildozer. Set to `buildozer ios debug` for iOS
    command: # default is buildozer android debug
    # Path to cloned repository. Set if you specified path for `actions/checkout` action.
    repository_root: # default is .
    # Working directory where buildozer.spec is located. Set to `src` if buildozer.spec is in `src` directory
    workdir: # default is .
    # Version of Buildozer to install. By default installs latest release
    buildozer_version: # default is stable
          
