# ফাইলের নাম: .github/workflows/main.yml

name: Build Android APK with Python-for-Android (Direct NDK Setup)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-android:
    name: Build APK with P4A
    runs-on: ubuntu-22.04

    steps:
      # ধাপ ১: রিপোজিটরির কোড চেকআউট করা
      - name: Checkout repository
        uses: actions/checkout@v4

      # ধাপ ২: Java 11 সেটআপ করা (p4a এর জন্য স্থিতিশীল)
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      # ধাপ ৩: সরাসরি NDK 25b ডাউনলোড এবং সেটআপ করা (সবচেয়ে গুরুত্বপূর্ণ এবং নির্ভরযোগ্য ধাপ)
      - name: Download and set up NDK 25b
        run: |
          # NDK 25b ডাউনলোড
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          # আনজিপ করা
          unzip -q android-ndk-r25b-linux.zip
          # এনভায়রনমেন্ট ভেরিয়েবল সেট করা যাতে p4a এটি খুঁজে পায়
          echo "ANDROID_NDK_HOME=$(pwd )/android-ndk-r25b" >> $GITHUB_ENV
          echo "NDK_VER=r25b" >> $GITHUB_ENV
          echo "NDK path set to: $(pwd)/android-ndk-r25b"

      # ধাপ ৪: Python এবং প্রয়োজনীয় লাইব্রেরি ইনস্টল করা
      - name: Set up Python and install dependencies
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - run: |
          pip install --upgrade pip
          pip install "cython<3.0"
          pip install python-for-android kivy==2.1.0

      # ধাপ ৫: Keystore তৈরি করা
      - name: Create Keystore
        env:
          KEY_PASSWORD: ${{ secrets.RELEASE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.RELEASE_ALIAS }}
        run: |
          keytool -genkey -v -keystore release.keystore -alias $KEY_ALIAS -keyalg RSA -keysize 2048 -validity 10000 -storepass $KEY_PASSWORD -keypass $KEY_PASSWORD -dname "CN=Md Samiul Islam, OU=Development, O=SamiulDev, L=Dhaka, ST=Dhaka, C=BD" -noprompt

      # ধাপ ৬: P4A দিয়ে APK বিল্ড করা
      - name: Build APK with P4A
        env:
          KEY_PASSWORD: ${{ secrets.RELEASE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.RELEASE_ALIAS }}
        run: |
          # p4a কে SDK স্বয়ংক্রিয়ভাবে ডাউনলোড করতে দেওয়া হচ্ছে
          p4a apk \
            --requirements=python3,kivy==2.1.0,android,jnius,sqlite3,openssl,requests,pillow,pyjnius \
            --package=com.samiul.minifire \
            --name="MINI FIRE" \
            --version=1.0.0 \
            --bootstrap=sdl2 \
            --dist_name=minifire \
            --arch=arm64-v8a \
            --orientation=portrait \
            --window \
            --release \
            --keystore=release.keystore \
            --keystore-password="$KEY_PASSWORD" \
            --signkey-alias="$KEY_ALIAS" \
            --signkey-password="$KEY_PASSWORD" \
            --private=.

      # ধাপ ৭: বিল্ড হওয়া APK ফাইল আপলোড করা
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: p4a-signed-apk
          path: ./*.apk
          
