name: Build with P4A

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          openjdk-11-jdk \
          git \
          wget \
          curl \
          unzip \
          zip

    - name: Download Compatible NDK
      run: |
        wget -q https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
        unzip -q android-ndk-r25b-linux.zip
        echo "ANDROID_NDK_HOME=$(pwd)/android-ndk-r25b" >> $GITHUB_ENV

    - name: Install P4A
      run: |
        pip3 install python-for-android kivy

    - name: Create Keystore
      env:
        KEY_PASSWORD: ${{ secrets.RELEASE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.RELEASE_ALIAS }}
      run: |
        keytool -genkey -v \
          -keystore release.keystore \
          -alias $KEY_ALIAS \
          -keyalg RSA -keysize 2048 -validity 10000 \
          -storepass $KEY_PASSWORD \
          -keypass $KEY_PASSWORD \
          -dname "CN=My App, OU=Development, O=MyCompany, L=Dhaka, ST=Dhaka, C=BD" \
          -noprompt

    - name: Build with P4A (Fixed Architecture)
      run: |
        p4a apk \
          --requirements=python3,kivy \
          --package=org.samiul.minifire \
          --name="MINI FIRE" \
          --version=1.0 \
          --bootstrap=sdl2 \
          --dist_name=minifire \
          --sdk_dir=$ANDROID_SDK_ROOT \
          --ndk_dir=$ANDROID_NDK_HOME \
          --android_api=33 \
          --arch=arm64-v8a \
          --arch=armeabi-v7a \
          --orientation=portrait \
          --window \
          --release \
          --keystore=release.keystore \
          --keystore-passwd:$KEY_PASSWORD \
          --signkey-alias=$KEY_ALIAS

    - name: Find APK Files
      run: |
        echo "=== Searching for APK ==="
        find . -name "*.apk" -type f
        find ~ -name "*.apk" -type f 2>/dev/null | head -10
        ls -la ~/.local/share/python-for-android/dists/minifire/dist/ 2>/dev/null || echo "No dist directory"

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: p4a-apk
        path: |
          ~/.local/share/python-for-android/dists/minifire/dist/*.apk
          ./dist/*.apk
        if-no-files-found: error
