name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install system dependencies (Ubuntu 24.04 compatible)
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git \
          build-essential \
          python3-pip \
          python3-venv \
          openjdk-17-jdk \
          zip \
          unzip \
          libssl-dev \
          zlib1g-dev \
          autoconf \
          automake \
          libtool \
          pkg-config \
          cmake \
          libffi-dev
        
    - name: Install Buildozer and Cython
      run: |
        pip install --upgrade pip
        # স্থির ভার্সনের বদলে直接从 GitHub এর master branch থেকে Buildozer ইনস্টল করুন
        pip install https://github.com/kivy/buildozer/archive/master.zip
        pip install cython==0.29.33
        
    - name: Build APK with manual license acceptance
      run: |
        # Force accept all Android licenses
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > ~/.android/adbkey
        echo "yes" | buildozer android debug 2>&1 | tee build.log
        
    - name: Verify APK creation
      run: |
        if ls bin/*.apk 1> /dev/null 2>&1; then
          echo "APK successfully created!"
          ls -la bin/
        else
          echo "Error: APK file not found!"
          ls -la bin/ || true
          exit 1
        fi
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: bin/*.apk
        retention-days: 30
        
    - name: Create Release (on tag push)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: bin/*.apk
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
