name: Build Android APK (Custom Environment)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-android:
    # আমরা একটি স্থিতিশীল এবং পরীক্ষিত রানার ব্যবহার করছি
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Java (JDK 17)
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip autoconf automake libtool build-essential libncurses5-dev
        sudo apt-get install -y libsdl2-2.0-0 libsdl2-image-2.0-0 libsdl2-mixer-2.0-0 libsdl2-ttf-2.0-0

    - name: Install Buildozer and dependencies
      run: |
        pip install "cython==0.29.36"
        pip install buildozer

    - name: Set up Android SDK and NDK
      run: |
        # SDK Command-line Tools ডাউনলোড এবং আনজিপ করা
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
        unzip commandlinetools-linux-8512546_latest.zip -d $ANDROID_HOME/cmdline-tools
        mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest

        # PATH কনফিগার করা যাতে sdkmanager খুঁজে পাওয়া যায়
        echo "export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools" >> $GITHUB_ENV

        # SDK প্ল্যাটফর্ম, বিল্ড টুলস এবং NDK ডাউনলোড ও লাইসেন্স গ্রহণ
        # আপনার spec ফাইল অনুযায়ী (API 33, NDK 25c, Build-Tools 33.0.2 )
        yes | sdkmanager "platforms;android-33" "build-tools;33.0.2" "ndk;25.2.9519653"

    - name: Add Buildozer to PATH
      run: |
        echo "/home/runner/.local/bin" >> $GITHUB_PATH

    - name: Build with Buildozer
      run: |
        # এখন একটি সম্পূর্ণ কাস্টম এবং নিয়ন্ত্রিত পরিবেশে বিল্ড চালানো হচ্ছে
        buildozer --verbose android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: bin/*.apk
        retention-days: 30
        
