name: Build Android APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Build custom Docker image
      run: |
        cat > Dockerfile << 'EOF'
        FROM ubuntu:22.04
        ENV DEBIAN_FRONTEND=noninteractive
        RUN apt-get update && apt-get install -y \
            python3 python3-pip git wget unzip openjdk-17-jdk \
            autoconf libtool pkg-config zlib1g-dev
        RUN pip3 install buildozer cython
        WORKDIR /app
        EOF
        
        docker build -t my-buildozer .
      
    - name: Run Buildozer with auto-accept
      run: |
        docker run --rm \
          -v "$(pwd)":/app \
          -w /app \
          my-buildozer \
          bash -c "yes | buildozer android debug"
      
    - name: Verify APK creation
      run: |
        if ls bin/*.apk 1> /dev/null 2>&1; then
          echo "✅ APK successfully created!"
          ls -la bin/
        else
          echo "❌ APK file not found!"
          exit 1
        fi
