name: Build Android APK with Docker

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image with non-root user
      run: |
        cat > Dockerfile << 'EOF'
        FROM ubuntu:22.04
        
        ENV DEBIAN_FRONTEND=noninteractive
        
        # System dependencies install
        RUN apt-get update && apt-get install -y \
            python3 python3-pip git wget unzip openjdk-17-jdk \
            autoconf automake libtool pkg-config zlib1g-dev \
            && apt-get clean
            
        # Non-root user create
        RUN useradd -m -u 1000 builder
        USER builder
        WORKDIR /home/builder
        
        # Buildozer install as non-root
        RUN pip3 install --user buildozer cython
        ENV PATH="/home/builder/.local/bin:${PATH}"
        
        WORKDIR /home/builder/app
        EOF
        
        docker build -t my-buildozer .

    - name: Run Buildozer with auto-accept
      run: |
        docker run --rm \
          -u 1000 \
          -v "$(pwd)":/home/builder/app \
          -w /home/builder/app \
          my-buildozer \
          bash -c "yes | buildozer android debug"

    - name: Check APK file
      run: |
        if ls bin/*.apk 1> /dev/null 2>&1; then
          echo "✅ APK successfully created!"
          ls -la bin/
        else
          echo "❌ APK file not found!"
          exit 1
        fi
