name: Build Android APK with Docker

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image with proper permissions
      run: |
        cat > Dockerfile << 'EOF'
        FROM ubuntu:22.04
        
        ENV DEBIAN_FRONTEND=noninteractive
        
        # System dependencies install
        RUN apt-get update && apt-get install -y \
            python3 python3-pip git wget unzip openjdk-17-jdk \
            autoconf automake libtool pkg-config zlib1g-dev \
            && apt-get clean
            
        # Create non-root user with proper UID that matches host
        RUN useradd -m -u 1001 builder
        USER builder
        WORKDIR /home/builder
        
        # Create app directory with proper permissions
        RUN mkdir -p /home/builder/app
        WORKDIR /home/builder/app
        
        # Buildozer install as non-root
        RUN pip3 install --user buildozer cython
        ENV PATH="/home/builder/.local/bin:${PATH}"
        EOF
        
        docker build -t my-buildozer .

    - name: Pre-create directories with proper permissions
      run: |
        mkdir -p .buildozer bin
        chmod 755 .buildozer bin

    - name: Run Buildozer with proper volume permissions
      run: |
        docker run --rm \
          -u 1001 \
          -v "$(pwd)":/home/builder/app \
          -w /home/builder/app \
          my-buildozer \
          bash -c "yes | buildozer android debug"
