name: Build MINI FIRE APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-22.04  # ✅ Ubuntu 22.04 use করছি (stable)
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git unzip openjdk-11-jdk \
          python3-pip autoconf libtool \
          pkg-config zlib1g-dev \
          libncurses5-dev libncursesw5-dev \
          libtinfo6 cmake libffi-dev libssl-dev \  # ✅ libtinfo6 instead of libtinfo5
          ninja-build curl
          
    - name: Install Buildozer
      run: pip install buildozer
      
    - name: Create minimal buildozer.spec
      run: |
        buildozer init
        # Override with minimal spec
        cat > buildozer.spec << EO
        
    - name: Build APK (with timeout)
      run: |
        timeout 1800 buildozer android debug || echo "Build may have timed out but continuing..."
        
    - name: Check for APK
      id: check-apk
      run: |
        if find bin/ -name "*.apk" | grep -q .; then
          echo "APK found!"
          echo "apk_exists=true" >> $GITHUB_OUTPUT
        else
          echo "No APK found"
          echo "apk_exists=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Upload APK
      if: steps.check-apk.outputs.apk_exists == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: MINI-FIRE-APK
        path: bin/*.apk
        retention-days: 30
        
    - name: Show build logs
      if: steps.check-apk.outputs.apk_exists == 'false'
      run: |
        echo "Build failed. Checking logs..."
        ls -la .buildozer/ || echo "No buildozer directory"
