name: Build Kivy App

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    strategy:
      matrix:
        arch: [arm64-v8a]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git zip unzip openjdk-17-jdk python3-pip autoconf automake libtool \
          build-essential libffi-dev libssl-dev python3-dev \
          pkg-config zlib1g-dev libtinfo5
        sudo libtoolize --force
      env:
        DEBIAN_FRONTEND: noninteractive

    - name: Install Buildozer and dependencies
      run: |
        python -m pip install --user --upgrade pip
        pip install --user buildozer==1.5.0 cython==0.29.33
        pip install --user kivy==2.1.0 kivymd==1.1.1 pillow
      env:
        pythonLocation: /opt/hostedtoolcache/Python/3.9.23/x64
        PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.9.23/x64/lib/pkgconfig
        Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.23/x64
        Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.23/x64
        Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.23/x64
        LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.23/x64/lib

    - name: Set up Android NDK
      run: |
        mkdir -p /home/runner/.buildozer/android/platform
        wget -q https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
        unzip -q android-ndk-r25b-linux.zip -d /home/runner/.buildozer/android/platform
        mv /home/runner/.buildozer/android/platform/android-ndk-r25b /home/runner/.buildozer/android/platform/android-ndk
      env:
        ANDROID_NDK_HOME: /home/runner/.buildozer/android/platform/android-ndk

    - name: Build with Buildozer
      run: |
        export GRADLE_OPTS="-Dorg.gradle.daemon=false -Dorg.gradle.configureondemand=true"
        export USE_CCACHE=1
        mkdir -p ~/.cache
        buildozer -v android debug
      env:
        ANDROID_SDK_ROOT: $ANDROID_HOME
        ANDROID_NDK_ROOT: /home/runner/.buildozer/android/platform/android-ndk

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: myapp-${{ matrix.arch }}.apk
        path: bin/*.apk
        retention-days: 30

    - name: Cleanup
      if: always()
      run: |
        rm -rf .buildozer
        rm -rf ~/.buildozer
