name: Build Kivy App

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        arch: [arm64-v8a]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build with Docker
      uses: kivy/buildozer-docker@v1.0.0
      with:
        command: buildozer android debug
        args: -v
        pull: always
        arch: ${{ matrix.arch }}

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: myapp-${{ matrix.arch }}.apk
        path: bin/*.apk
        retention-days: 30
