# ফাইলের নাম: .github/workflows/main.yml

name: Build Kivy Android App (Release APK)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-android:
    name: Build Signed Release APK
    runs-on: ubuntu-22.04

    steps:
      # ধাপ ১: রিপোজিটরির কোড চেকআউট করা
      - name: Checkout repository
        uses: actions/checkout@v4

      # ধাপ ২: সিস্টেম ডিপেন্ডেন্সি ইনস্টল করা
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git \
            zip \
            unzip \
            openjdk-11-jdk \
            python3-pip \
            python3-setuptools \
            autoconf \
            build-essential \
            libssl-dev \
            libffi-dev \
            python3-venv \
            wget \
            curl \
            libncurses5 \
            zlib1g-dev

      # ধাপ ৩: Python এবং Buildozer সেটআপ করা
      - name: Set up Python and Buildozer
        run: |
          python3 --version
          pip3 install --upgrade pip wheel setuptools
          pip3 install buildozer cython==0.29.33 virtualenv

      # ধাপ ৪: Buildozer ডিরেক্টরি স্ট্রাকচার তৈরি করা
      - name: Setup Buildozer directories
        run: |
          mkdir -p ~/.buildozer/android/packages
          mkdir -p ~/.buildozer/android/platform

      # ধাপ ৫: Keystore তৈরি করা
      - name: Generate Keystore
        env:
          RELEASE_PASSWORD: ${{ secrets.RELEASE_PASSWORD }}
          RELEASE_ALIAS: ${{ secrets.RELEASE_ALIAS }}
        run: |
          echo "Generating Keystore..."
          keytool -genkey -v \
            -keystore release.keystore \
            -alias $RELEASE_ALIAS \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -storepass $RELEASE_PASSWORD \
            -keypass $RELEASE_PASSWORD \
            -dname "CN=Md Samiul Islam, OU=Development, O=SamiulDev, L=Dhaka, ST=Dhaka, C=BD" \
            -noprompt
          echo "Keystore generated successfully."

      # ধাপ ৬: buildozer.spec আপডেট করা
      - name: Update buildozer.spec for release
        env:
          RELEASE_PASSWORD: ${{ secrets.RELEASE_PASSWORD }}
          RELEASE_ALIAS: ${{ secrets.RELEASE_ALIAS }}
        run: |
          echo "Updating buildozer.spec for release signing..."
          sed -i "s|android.release_key.alias = .*|android.release_key.alias = $RELEASE_ALIAS|" buildozer.spec
          sed -i "s|android.release_key.store_password = .*|android.release_key.store_password = $RELEASE_PASSWORD|" buildozer.spec
          sed -i "s|android.release_key.alias_password = .*|android.release_key.alias_password = $RELEASE_PASSWORD|" buildozer.spec
          echo "Updated buildozer.spec successfully"

      # ধাপ ৭: Buildozer কনফিগারেশন আপডেট করা
      - name: Configure Buildozer for first build
        run: |
          echo "Configuring Buildozer for first build..."
          # Buildozer কে force করে প্রথমে সব ডাউনলোড করতে বলা
          buildozer android update 2>&1 | tee download.log || echo "Download started, continuing..."
          sleep 10

      # ধাপ ৮: APK বিল্ড করা (সরাসরি release)
      - name: Build Release APK
        run: |
          echo "Starting release APK build..."
          # লগ লেভেল 2 সেট করে বিস্তারিত লগ দেখানো
          buildozer -v android release 2>&1 | tee build.log
          
          # যদি APK তৈরি হয়ে থাকে
          if ls bin/*.apk 1> /dev/null 2>&1; then
            echo "APK built successfully!"
            ls -la bin/
          else
            echo "APK not found, checking logs..."
            cat build.log
            exit 1
          fi

      # ধাপ ৯: APK আপলোড করা
      - name: Upload Signed APK
        uses: actions/upload-artifact@v4
        with:
          name: signed-release-apk
          path: bin/*.apk
          retention-days: 7

      # ধাপ ১০: বিল্ড লগ সংরক্ষণ
      - name: Upload Build Logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-logs
          path: |
            build.log
            download.log
            .buildozer/
          retention-days: 3
