name: Build Kivy Android App (Release APK)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-android:
    name: Build Signed Release APK
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip openjdk-11-jdk \
            python3-pip python3-setuptools \
            autoconf build-essential \
            libssl-dev libffi-dev \
            wget curl

      - name: Set up Python and Buildozer
        run: |
          pip3 install --upgrade pip
          pip3 install buildozer cython==0.29.33

      - name: Generate Keystore
        env:
          RELEASE_PASSWORD: ${{ secrets.RELEASE_PASSWORD }}
          RELEASE_ALIAS: ${{ secrets.RELEASE_ALIAS }}
        run: |
          keytool -genkey -v \
            -keystore release.keystore \
            -alias $RELEASE_ALIAS \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -storepass $RELEASE_PASSWORD \
            -keypass $RELEASE_PASSWORD \
            -dname "CN=Md Samiul Islam, OU=Development, O=SamiulDev, L=Dhaka, ST=Dhaka, C=BD" \
            -noprompt

      - name: Build APK with System NDK
        env:
          ANDROID_NDK_HOME: ${{ env.ANDROID_NDK_ROOT }}
          ANDROID_SDK_HOME: ${{ env.ANDROID_SDK_ROOT }}
        run: |
          echo "Using System NDK: $ANDROID_NDK_ROOT"
          echo "Using System SDK: $ANDROID_SDK_ROOT"
          
          # Force buildozer to use system NDK/SDK
          export ANDROIDSDK="$ANDROID_SDK_ROOT"
          export ANDROIDNDK="$ANDROID_NDK_ROOT"
          
          buildozer -v android release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: bin/*.apk
