name: Build Kivy APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython==0.29.36
          pip install buildozer

      - name: Install Buildozer Requirements
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk python3-dev git zip unzip

      - name: Initialize Buildozer
        run: |
          buildozer init
          buildozer android debug

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my_app_apk
          path: bin/*.apk
