# ফাইলের নাম: .github/workflows/samiul-gemini.yml

name: Build Android APK (Option 2 - AAR Integration)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-android:
    name: Build APK with P4A - Option 2
    runs-on: ubuntu-22.04

    steps:
      # ধাপ ১: রিপোজিটরির কোড চেকআউট করা
      - name: Checkout repository
        uses: actions/checkout@v4

      # ধাপ ২: Java 17 সেটআপ করা
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # ধাপ ৩: NDK 25b ডাউনলোড এবং সেটআপ
      - name: Download and set up NDK 25b
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip -O android-ndk-r25b-linux.zip
          unzip -q android-ndk-r25b-linux.zip
          echo "ANDROID_NDK_HOME=$(pwd)/android-ndk-r25b" >> $GITHUB_ENV
          echo "NDK path set to: $(pwd)/android-ndk-r25b"

      # ধাপ ৪: Python 3.11 সেটআপ করা
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      # ধাপ ৫: পাইথন লাইব্রেরি ইনস্টল করা
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install "cython==0.29.37"
          pip install "kivy==2.3.0"
          pip install "python-for-android==2024.1.21"

      # ধাপ ৬: Smart Start.io SDK ডাউনলোড করা (Auto Version Detection)
      - name: Download Compatible Start.io SDK
        run: |
          mkdir -p libs
          echo "Finding compatible Start.io SDK version..."
          
          # Available versions list (সবচেয়ে compatible থেকে শুরু)
          VERSIONS=("4.9.3" "4.10.7" "4.8.8" "4.11.4" "4.7.0" "4.6.0" "4.5.0")
          
          for version in "${VERSIONS[@]}"; do
            echo "Trying version: $version"
            URL="https://repo1.maven.org/maven2/com/startapp/inapp-sdk/$version/inapp-sdk-$version.aar"
            
            # Download attempt
            if wget --timeout=30 -O "libs/inapp-sdk-$version.aar" "$URL"; then
              echo "✅ Successfully downloaded version $version"
              
              # File verification
              if [ -s "libs/inapp-sdk-$version.aar" ]; then
                echo "✅ File verified: $(wc -c < libs/inapp-sdk-$version.aar) bytes"
                # Use this version
                mv "libs/inapp-sdk-$version.aar" "libs/inapp-sdk.aar"
                echo "SELECTED_VERSION=$version" >> $GITHUB_ENV
                break
              else
                echo "❌ File empty, trying next version..."
                rm -f "libs/inapp-sdk-$version.aar"
              fi
            else
              echo "❌ Download failed for $version, trying next..."
            fi
          done
          
          # Final check
          if [ -f "libs/inapp-sdk.aar" ]; then
            echo "🎉 Compatible version found: $SELECTED_VERSION"
            ls -la libs/inapp-sdk.aar
          else
            echo "💥 No compatible version found!"
            exit 1
          fi

      # ধাপ ৭: Keystore তৈরি করা
      - name: Create Keystore
        env:
          KEY_PASSWORD: ${{ secrets.RELEASE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.RELEASE_ALIAS }}
        run: |
          keytool -genkey -v -keystore release.keystore -alias "$KEY_ALIAS" -keyalg RSA -keysize 2048 -validity 10000 -storepass "$KEY_PASSWORD" -keypass "$KEY_PASSWORD" -dname "CN=Md Samiul Islam, OU=Development, O=SamiulDev, L=Dhaka, ST=Dhaka, C=BD" -noprompt

      # ধাপ ৮: P4A দিয়ে APK বিল্ড করা (Option 2 - Alternative AAR Integration)
      - name: Build APK with P4A
        env:
          KEY_PASSWORD: ${{ secrets.RELEASE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.RELEASE_ALIAS }}
        run: |
          find android-ndk-r25b -name "*.py" -delete
          
          echo "Using Start.io version: $SELECTED_VERSION"
          
          echo "=== Step 1: Copying AAR to p4a dist ==="
          mkdir -p /home/runner/.local/share/python-for-android/dists/minifire/libs
          cp libs/inapp-sdk.aar /home/runner/.local/share/python-for-android/dists/minifire/libs/
          echo "AAR copied successfully"
          
          echo "=== Step 2: Building APK with internal AAR path ==="
          p4a apk \
            --requirements=python3,kivy==2.3.0,jnius,sqlite3,openssl \
            --package=com.samiul.minifire \
            --name="MINI FIRE" \
            --version=1.0.0 \
            --bootstrap=sdl2 \
            --dist_name=minifire \
            --arch=arm64-v8a \
            --orientation=portrait \
            --window \
            --release \
            --android-api=34 \
            --permission=INTERNET \
            --permission=ACCESS_NETWORK_STATE \
            --add-aar=/home/runner/.local/share/python-for-android/dists/minifire/libs/inapp-sdk.aar \
            --keystore=release.keystore \
            --keystorepw="$KEY_PASSWORD" \
            --signkey="$KEY_ALIAS" \
            --signkeypw="$KEY_PASSWORD" \
            --private=. \
            --ignore-setup-py

      # ধাপ ৯: বিল্ড হওয়া APK ফাইল আপলোড করা
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: minifire-signed-apk
          path: ./*.apk

      # ধাপ ১০: সাফল্য মেসেজ
      - name: Success Message
        run: |
          echo "🎉 APK বিল্ড সফলভাবে সম্পন্ন হয়েছে!"
          echo "📱 APK ফাইল আপলোড করা হয়েছে আর্টিফ্যাক্ট হিসেবে"
          echo "🔥 Start.io Version: $SELECTED_VERSION"
          echo "🚀 এখন আপনি APK ডাউনলোড করতে পারবেন"
