# ফাইলের নাম: .github/workflows/samiul-gemini.yml

name: Build Android APK (No Signing)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-android:
    name: Build Unsigned APK
    runs-on: ubuntu-22.04

    steps:
      # ধাপ ১: রিপোজিটরির কোড চেকআউট করা
      - name: Checkout repository
        uses: actions/checkout@v4

      # ধাপ ২: Java 17 সেটআপ করা
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # ধাপ ৩: NDK 25b ডাউনলোড এবং সেটআপ
      - name: Download and set up NDK 25b
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip -O android-ndk-r25b-linux.zip
          unzip -q android-ndk-r25b-linux.zip
          echo "ANDROID_NDK_HOME=$(pwd)/android-ndk-r25b" >> $GITHUB_ENV

      # ধাপ ৪: Python 3.11 সেটআপ করা
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      # ধাপ ৫: পাইথন লাইব্রেরি ইনস্টল করা
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install "cython==0.29.37"
          pip install "kivy==2.3.0"
          pip install "python-for-android==2024.1.21"

      # ধাপ ৬: Start.io Ads SDK ডাউনলোড করা
      - name: Download Start.io Ads SDK
        run: |
          mkdir -p libs
          wget https://repo1.maven.org/maven2/com/startapp/inapp-sdk/4.11.4/inapp-sdk-4.11.4.aar -O libs/inapp-sdk.aar

      # ধাপ ৭: P4A দিয়ে APK বিল্ড করা (unsigned)
      - name: Build APK with P4A
        run: |
          p4a apk \
            --requirements=python3,kivy==2.3.0,jnius,sqlite3,openssl \
            --package=com.samiul.minifire \
            --name="MINI FIRE" \
            --version=1.0.0 \
            --bootstrap=sdl2 \
            --dist_name=minifire \
            --arch=arm64-v8a \
            --orientation=portrait \
            --window \
            --android-api=34 \
            --permission=INTERNET \
            --permission=ACCESS_NETWORK_STATE \
            --add-aar=libs/inapp-sdk.aar \
            --private=. \
            --verbose

      # ধাপ ৮: বিল্ড হওয়া APK ফাইল আপলোড করা
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-apk
          path: ./*.apk
